image: python:3.5

style:
  stage: test
  script:
    - pip install -e .[dev]
    - pre-commit run --all-files

test:
  stage: test
  script:
    - pip install -e .[dev]
    - pytest

deploy:
    stage: deploy
    script:
        - pip install -e .[dev]
        - s3pypi --bucket cmv-pkg-shed --private
    only:
        - tags
