strictness: medium
pylint:
  disable:
    # Unused arguments are often needed to conform to an expected signature.
    - unused-argument
    # Pylint is sometimes quite bad at the type inference necessary for these.
    - unsubscriptable-object
    - unsupported-membership-test
    # This one is too picky (it complains about *args, **kwargs) and errors of
    # this type are trivial to catch with minimal actual testing
    - arguments-differ
pep8:
  options:
    max-line-length: 79
