# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSPDirective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('default-src', 'default-src'), ('script-src', 'script-src'), ('object-src', 'object-src'), ('style-src', 'style-src'), ('img-src', 'img-src'), ('media-src', 'media-src'), ('frame-src', 'frame-src'), ('font-src', 'font-src'), ('connect-src', 'connect-src'), ('sandbox', 'sandbox'), ('report-uri', 'report-uri'), ('base-uri', 'base-uri'), ('child-src', 'child-src'), ('form-action', 'form-action'), ('frame-ancestors', 'frame-ancestors'), ('manifest-src', 'manifest-src'), ('worker-src', 'worker-src'), ('plugin-types', 'plugin-types'), ('require-sri-for', 'require-sri-for'), ('upgrade-insecure-requests', 'upgrade-insecure-requests'), ('block-all-mixed-content', 'block-all-mixed-content')], max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CSPDirectiveValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('directive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directive_values', to='csp_admin.CSPDirective')),
            ],
        ),
    ]
