# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_admin', '0002_auto_20171229_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cspdirectivevalue',
            options={'verbose_name': 'CSP Directive Value'},
        ),
        migrations.AddField(
            model_name='cspdirective',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
